version: "3.7"

services:
    
    tech-attic-node:
        image: ratneshmurugesan/tech-attic-node:dev
        build: 
            context: .
            target: dev
            container_name: tech-attic-node
            restart: always
            volumes: 
                - .:/app
            ports:
                - "5000:5000"
                # - "3000:3000"
            # networks:
            #     -  tech-attic-node-network

    # networks:
    #     tech-attic-node-network:
    #         name:  tech-attic-node-network
