const time_aggregate = [
  { id: "dateindex", name: "Daily" },
  { id: "weekindex", name: "Weekly Aggregation" },
  { id: "monthindex", name: "Monthly Aggregation" },
  { id: "quarterindex", name: "Quarterly Aggregation" },
];
const channels = [
  { id: 4, name: "Programmatic" },
  { id: 3, name: "Direct" },
  { id: 2, name: "Social" },
  { id: 1, name: "Search" },
];
const platforms = [
  { id: 1, name: "Google Ad Search", channelId: 1 },
  { id: 2, name: "LinkedIn", channelId: 2 },
  { id: 3, name: "Facebook", channelId: 2 },
  { id: 4, name: "Instagram", channelId: 2 },
  { id: 5, name: "Twitter", channelId: 2 },
  { id: 6, name: "Bing", channelId: 1 },
  { id: 7, name: "DV360", channelId: 4 },
];
const conversion_source = [
  { id: 1, name: "CM", values: ["SA360", "DCM"] },
  {
    id: 2,
    name: "FB+LI+TW+YT+DV360+GOOG+BING",
    values: ["Facebook", "LinkedIn", "Google Ad Search", "Bing", "DV360"],
  },
];
const geo = [
  { id: 2, name: "USA" },
  { id: 1, name: "Global" },
];
const campaign_brands = [
  { id: 3, name: "Women" },
  { id: 2, name: "US Exec" },
  { id: 1, name: "Core" },
];

const campaign_subscription = [
  { id: 1, name: "Get 30% off on any subscription" },
  { id: 2, name: "Get 50% off on Virtual Class subscription" },
];

const keywords = [
  { id: 3, name: "Reviews" },
  { id: 2, name: "Classes" },
  { id: 1, name: "Exams" },
];

const regions = [
  { id: 3, name: "USA" },
  { id: 2, name: "EMEA" },
  { id: 1, name: "APAC" },
];

const buckets = [
  { id: 3, name: "Applications" },
  { id: 2, name: "Prospects" },
  { id: 1, name: "Leads" },
];

const programs = [
  { id: 10, name: "CCV", categoryId: 2 },
  { id: 9, name: "LCV", categoryId: 2 },

  { id: 8, name: "SATV", categoryId: 1 },
  { id: 7, name: "PCDV", categoryId: 1 },
  { id: 6, name: "Governance", categoryId: 1 },
  { id: 5, name: "FSEV", categoryId: 1 },
  { id: 4, name: "DPGV", categoryId: 1 },
  { id: 3, name: "BEV", categoryId: 1 },

  { id: 2, name: "GMP", categoryId: 3 },
  { id: 1, name: "AMP", categoryId: 3 },
];

const categories = [
  { id: 3, name: "CLP" },
  { id: 2, name: "Virtual" },
  { id: 1, name: "Category / Program" },
];
const group_value = [
  { id: 5, name: "AGB" },
  { id: 4, name: "DIGS" },
  { id: 3, name: "HPLP" },
  { id: 2, name: "OPM" },
  { id: 1, name: "GMM" },
];
const targeting_type = [
  { id: 4, name: "Affinity & Marketing" },
  { id: 3, name: "Contextual Keywords" },
  { id: 2, name: "Retargeting" },
  { id: 1, name: "Lookalikes" },
];

// Metrics
const metrics = [
  { id: 1, name: "visits" },
  { id: 2, name: "spend" },
  { id: 3, name: "leads" },
  { id: 4, name: "prospects" },
  { id: 5, name: "applications" },
  { id: 6, name: "va" },

  { id: 7, name: "cpv" },
  { id: 8, name: "cpl" },
  { id: 9, name: "cpp" },
  { id: 10, name: "cpa" },
  { id: 11, name: "cpva" },
  { id: 12, name: "cpc" },
  { id: 13, name: "conversions" },

  { id: 14, name: "clicks" },
  { id: 15, name: "impressions" },
];

const device = [
  { id: 1, name: "Desktop" },
  { id: 2, name: "Mobile" },
];

const campaignAudiences = [
  { id: 1, name: "Client Past Purchasers" },
  { id: 2, name: "Client Past Visitors" },
];

const campaignTypes = [
  { id: 1, name: "Brand Awareness" },
  { id: 2, name: "Re-targeting" },
  { id: 3, name: "Conversion" },
  { id: 4, name: "Leads generation" },
]; //

const promotionType = [
  { id: 1, name: "Evergreen" },
  { id: 2, name: "Promo" },
];


const brandNonBrand = [
  { id: 1, name: "Brand" },
  { id: 2, name: "Non Brand" },
];

const match_type = [
  { id: 1, name: "Broad" },
  { id: 2, name: "Exact" },
];

const dma_regions = [
  { name: "Abilene-Sweetwater, TX", id: 1 },
  { name: "Albany-Schenectady-Troy, NY", id: 2 },
  { name: "Albany, GA", id: 3 },
  { name: "Albuquerque-Santa Fe, NM", id: 4 },
  { name: "Alexandria, LA", id: 5 },
  { name: "Alpena, MI", id: 6 },
  { name: "Amarillo, TX", id: 7 },
  { name: "Anchorage, AK", id: 8 },
  { name: "Atlanta, GA", id: 9 },
  { name: "Augusta, GA", id: 10 },
  { name: "Austin, TX", id: 11 },
  { name: "Bakersfield, CA", id: 12 },
  { name: "Baltimore, MD", id: 13 },
  { name: "Bangor, ME", id: 14 },
  { name: "Baton Rouge, LA", id: 15 },
  { name: "Beaumont-Port Arthur, TX", id: 16 },
  { name: "Bend, OR", id: 17 },
  { name: "Billings, MT", id: 18 },
  { name: "Biloxi-Gulfport, MS", id: 19 },
  { name: "Binghamton, NY", id: 20 },
  { name: "Birmingham, AL", id: 21 },
  { name: "Bluefield-Beckley-Oak Hill, WV", id: 22 },
  { name: "Boise, ID", id: 23 },
  { name: "Boston, MA-Manchester, NH", id: 24 },
  { name: "Bowling Green, KY", id: 25 },
  { name: "Buffalo, NY", id: 26 },
  { name: "Burlington, VT-Plattsburgh, NY", id: 27 },
  { name: "Butte-Bozeman, MT", id: 28 },
  { name: "Casper-Riverton, WY", id: 29 },
  { name: "Cedar Rapids-Waterloo-Iowa City & Dubuque, IA", id: 30 },
  { name: "Champaign & Springfield-Decatur,IL", id: 31 },
  { name: "Charleston-Huntington, WV", id: 32 },
  { name: "Charleston, SC", id: 33 },
  { name: "Charlotte, NC", id: 34 },
  { name: "Charlottesville, VA", id: 35 },
  { name: "Chattanooga, TN", id: 36 },
  { name: "Cheyenne, WY-Scottsbluff, NE", id: 37 },
  { name: "Chicago, IL", id: 38 },
  { name: "Chico-Redding, CA", id: 39 },
  { name: "Cincinnati, OH", id: 40 },
  { name: "Clarksburg-Weston, WV", id: 41 },
  { name: "Cleveland-Akron (Canton), OH", id: 42 },
  { name: "Colorado Springs-Pueblo, CO", id: 43 },
  { name: "Columbia-Jefferson City, MO", id: 44 },
  { name: "Columbia, SC", id: 45 },
  { name: "Columbus, GA", id: 46 },
  { name: "Columbus, OH", id: 47 },
  { name: "Columbus-Tupelo-West Point, MS", id: 48 },
  { name: "Corpus Christi, TX", id: 49 },
  { name: "Dallas-Ft. Worth, TX", id: 50 },
  { name: "Davenport,IA-Rock Island-Moline,IL", id: 51 },
  { name: "Dayton, OH", id: 52 },
  { name: "Denver, CO", id: 53 },
  { name: "Des Moines-Ames, IA", id: 54 },
  { name: "Detroit, MI", id: 55 },
  { name: "Dothan, AL", id: 56 },
  { name: "Duluth, MN-Superior, WI", id: 57 },
  { name: "El Paso, TX", id: 58 },
  { name: "Elmira, NY", id: 59 },
  { name: "Erie, PA", id: 60 },
];

// Campaigns
const campaigns = [
  {
    id: 1,
    promotion: 2,
    name: "Campaign I",
    type: 1,
    audience: 2,
    device: 1,
    asset: 4,
    placement: 1,
    brand: 1,
    parent: "Audience I",
    program: 6,
    headline: "Client CPA course",
    body: "Structured course",
    description: "Client offers CPA course for professionals",
    promotionType: 1,
    creative: "Single Part Course",

    geo: 1,
    groupValue: 4,
    targetingType: 2,
    conversionSource: 1,

    channels: 2,
    platforms: 3,
    campaignBrands: 3,
    buckets: 3,
    categories: 1,
    region: 2,
    campaign_subscription: 2,
    match_type: 1,
    keyword: 1,
    keywordCat: "Exams",
    keyword_text: "cpa far exams",
  },
  {
    id: 2,
    promotion: 1,
    name: "Campaign II",
    type: 2,
    audience: 1,
    media: 2,
    brand: 2,
    parent: "Audience II",
    program: 9,
    creativeTheme: 1,
    creativeSize: 1,
    creativeVideoSize: 1,

    geo: 2,
    groupValue: 2,
    targetingType: 4,
    conversionSource: 1,

    channels: 4, // Progra
    platforms: 7, //DV360
    campaignBrands: 2,
    buckets: 2,
    categories: 2,
    region: 1,
    campaign_subscription: 1,
    match_type: 2,
    keyword: 3,
    keywordCat: "Reviews",
    keyword_text: "cpe review",
  },
  {
    id: 3,
    promotion: 3,
    name: "Campaign III",
    type: 3,
    audience: 2,
    parent: "Audience III",
    program: 1,
    brand: 1,
    headlineOne: "Client CPE course",
    headlineTwo: "Structured course",
    headlineThree: "3 years",
    descriptionOne: "Client offers CPA course for professionals",
    descriptionTwo: "CPA courses offer by Client for professionals",
    siteLinks: "Single Part Courses",
    callOuts: "24-7 customer support",

    geo: 1,
    groupValue: 1,
    targetingType: 1,
    conversionSource: 1,

    channels: 1,
    platforms: 1, //Google
    campaignBrands: 1,
    buckets: 1,
    categories: 3,
    region: 3,
    campaign_subscription: 2,
    match_type: 1,
    keyword: 2,
    keywordCat: "Classes",
    keyword_text: "virtual classes",
  },
  {
    id: 4,
    promotion: 4,
    name: "Campaign IV",
    type: 4,
    audience: 2,
    device: 2,
    asset: 1,
    brand: 2,
    placement: 4,
    parent: "Audience I",
    program: 4,
    headline: "Client CPE course",
    body: "Established since 1905",
    description: "Client offers CPE course for professionals",
    promotionType: 1,
    creative: "Replacements & Upgrades",

    geo: 2,
    groupValue: 1,
    targetingType: 3,
    conversionSource: 1,

    channels: 2,
    platforms: 2, //LI
    campaignBrands: 3,
    buckets: 3,
    categories: 1,
    region: 2,
    campaign_subscription: 1,
    match_type: 2,
    keyword: 1,
    keywordCat: "Exams",
    keyword_text: "exams on management",
  },
  {
    id: 5,
    promotion: 5,
    name: "Campaign V",
    type: 1,
    audience: 1,
    parent: "Audience II",
    program: 10,
    brand: 2,
    headlineOne: "Client CPA course",
    headlineTwo: "Structured course",
    headlineThree: "4 years",
    descriptionOne: "Client offers CPE course for professionals",
    descriptionTwo: "CPE courses offered",
    siteLinks: "Replacements & Upgrades",
    callOuts: "Established since 1905",

    geo: 2,
    groupValue: 4,
    targetingType: 1,
    conversionSource: 1,

    channels: 1, //
    platforms: 6, //Bing
    campaignBrands: 2,
    buckets: 2,
    categories: 2,
    region: 1,
    campaign_subscription: 2,
    match_type: 1,
    keyword: 3,
    keywordCat: "Reviews",
    keyword_text: "reviews on management course",
  },
  {
    id: 6,
    promotion: 2,
    name: "Campaign I",
    type: 1,
    audience: 2,
    device: 1,
    asset: 4,
    brand: 1,
    placement: 1,
    parent: "Audience I",
    program: 6,
    headline: "Client CPA course",
    body: "Structured course",
    description: "Client offers CPA course for professionals",
    promotionType: 1,
    creative: "Single Part Course",

    geo: 1,
    groupValue: 4,
    targetingType: 2,
    conversionSource: 1,

    channels: 2,
    platforms: 3,
    campaignBrands: 3,
    buckets: 3,
    categories: 1,
    region: 2,
    campaign_subscription: 1,
    match_type: 2,
    keyword: 2,
    keywordCat: "Classes",
    keyword_text: "classes gm",
  },
  {
    id: 7,
    promotion: 1,
    name: "Campaign II",
    type: 2,
    audience: 1,
    media: 2,
    parent: "Audience II",
    program: 9,
    brand: 2,
    creativeTheme: 1,
    creativeSize: 1,
    creativeVideoSize: 1,

    geo: 2,
    groupValue: 2,
    targetingType: 4,
    conversionSource: 1,

    channels: 4, // Progra
    platforms: 7, //DV360
    campaignBrands: 2,
    buckets: 2,
    categories: 2,
    region: 1,
    campaign_subscription: 2,
    match_type: 1,
    keyword: 1,
    keywordCat: "Exams",
    keyword_text: "exam 1",
  },
  {
    id: 8,
    promotion: 3,
    name: "Campaign III",
    type: 3,
    audience: 2,
    parent: "Audience III",
    program: 6,
    brand: 1,
    headlineOne: "Client CPE course",
    headlineTwo: "Structured course",
    headlineThree: "3 years",
    descriptionOne: "Client offers CPA course for professionals",
    descriptionTwo: "CPA courses offer by Client for professionals",
    siteLinks: "Single Part Courses",
    callOuts: "24-7 customer support",

    geo: 1,
    groupValue: 1,
    targetingType: 1,
    conversionSource: 1,

    channels: 1,
    platforms: 1, //Google
    campaignBrands: 1,
    buckets: 1,
    categories: 1,
    region: 3,
    campaign_subscription: 1,
    match_type: 2,
    keyword: 1,
    keywordCat: "Exams",
    keyword_text: "+exams",
  },
  {
    id: 9,
    promotion: 4,
    name: "Campaign IV",
    type: 4,
    audience: 2,
    device: 2,
    asset: 1,
    placement: 4,
    brand: 2,
    parent: "Audience I",
    program: 5,
    headline: "Client CPE course",
    body: "Established since 1905",
    description: "Client offers CPE course for professionals",
    promotionType: 1,
    creative: "Replacements & Upgrades",

    geo: 2,
    groupValue: 1,
    targetingType: 3,
    conversionSource: 1,

    channels: 2,
    platforms: 2, //LI
    campaignBrands: 3,
    buckets: 3,
    categories: 1,
    region: 2,
    campaign_subscription: 2,
    match_type: 1,
    keyword: 2,
    keywordCat: "Classes",
    keyword_text: "+classes",
  },
  {
    id: 10,
    promotion: 5,
    name: "Campaign V",
    type: 1,
    audience: 1,
    parent: "Audience II",
    program: 3,
    brand: 2,
    headlineOne: "Client CPE course",
    headlineTwo: "Structured course",
    headlineThree: "4 years",
    descriptionOne: "Client offers CPE course for professionals",
    descriptionTwo: "CPE courses offered",
    siteLinks: "Replacements & Upgrades",
    callOuts: "Established since 1905",

    geo: 1,
    groupValue: 4,
    targetingType: 1,
    conversionSource: 1,

    channels: 1, //
    platforms: 6, //Bing
    campaignBrands: 2,
    buckets: 2,
    categories: 1,
    region: 1,
    campaign_subscription: 1,
    match_type: 2,
    keyword: 3,
    keywordCat: "Reviews",
    keyword_text: "reviews courses",
  },
];

module.exports = {
  device,
  promotionType,
  campaignTypes,
  campaignAudiences,

  brandNonBrand,
  metrics,
  campaign_subscription,
  campaigns,
  programs,
  keywords,
  regions,
  match_type,
  time_aggregate,
  channels,
  platforms,
  conversion_source,
  geo,
  campaign_brands,
  buckets,
  categories,
  group_value,
  targeting_type,
  dma_regions,
};
